sudo: false

language: node_js

node_js:
  - "6"
  - "7"
  - node

dist: trusty

cache: yarn

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - yarn global add @angular/cli
  - yarn global add angular-cli-ghpages

install:

before_script:

script:
  - yarn test
  - yarn e2e
  - ng build --prod --aot --base-href="https://puku0x.github.io/angular-onsenui2-webpack2/"
  - angular-cli-ghpages --dir="www" --repo="https://GH_TOKEN@puku0x.github.io/angular-onsenui2-webpack2.git" --name="build bot" --email="puku0x@gmail.com"
