sudo: false

language: node_js

node_js:
  - "6"
  - "7"
  - node

dist: trusty

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:
  - yarn test
  - yarn e2e
  - ng build --prod --aot --base-href="https://puku0x.github.io/angular-onsenui2-webpack2/"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: www
  on:
    branch: master
