sudo: false

language: node_js

node_js:
  - "6"
  - "7"
  - node

dist: trusty

cache: yarn

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - xvfb

before_install:

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - yarn install

script:
  - yarn test
  - yarn e2e
  - yarn build:prod
